name: Trickdriver Main Branch CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, bcmath, pdo_pgsql

      - name: Install Composer dependencies
        working-directory: ./core
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Install PHP_CodeSniffer
        working-directory: ./core
        run: composer require --dev squizlabs/php_codesniffer

      - name: Run PHP_CodeSniffer
        working-directory: ./core
        run: composer run lint
  pgsql:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:14
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: forge
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        os: [ ubuntu-latest ]
      fail-fast: true

    name: PostgreSQL 14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_pgsql, :php-psr
          tools: composer:v2
          coverage: none

      - name: Set Framework version
        run: composer config version "11.x-dev"

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit tests/Integration/Database
        env:
          DB_CONNECTION: pgsql
          DB_USERNAME: forge
          DB_PASSWORD: password

  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, bcmath, pdo_pgsql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
        working-directory: ./core

      - name: Copy .env file
        run: cp .env.example .env
        working-directory: ./core

      - name: Update .env for testing
        run: |
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=pgsql/' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=postgres/' .env
          sed -i 's/DB_PORT=3306/DB_PORT=5432/' .env
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=test_db/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=postgres/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=password/' .env
        working-directory: ./core

      - name: Generate application key
        run: php artisan key:generate
        working-directory: ./core

      - name: Run migrations
        run: php artisan migrate --force
        working-directory: ./core

      - name: Run PHPUnit tests
        run: php artisan test
        working-directory: ./core
