name: PostgreSQL Tests

on:
  - push
  - pull_request

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PWD }}
          POSTGRES_DB: db_test_laravel
        ports:
          - 55432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.3']

    name: P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.dependency-stability }} - ${{ matrix.operating-system}}

    steps:
      - uses: actions/checkout@v4

      - name: Install PHP versions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Get Composer Cache Directory 2
        id: composer-cache
        working-directory: ./core
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: actions-cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Cache PHP dependencies
        uses: actions/cache@v4
        id: vendor-cache
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Install Laravel Dependencies
        working-directory: ./core
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Show dir
        run: pwd

      - name: PHP Version
        run: php --version

      - name: Generate Application Keys
        working-directory: ./core
        run: cp .env.example .env && php artisan key:generate

      - name: Running the migrations
        working-directory: ./core
        env:
          DB_CONNECTION: pgsql
          DB_DATABASE: db_test_laravel
          DB_PORT: 55432
          DB_USERNAME: ${{ secrets.TEST_DB_USER }}
          DB_PASSWORD: ${{ secrets.TEST_DB_PWD }}
          CIPHERSWEET_KEY: ${{ secrets.CIPHERSWEET_KEY }}
        run: |
          php artisan migrate:fresh --seed --env=testing
          php artisan ciphersweet:encrypt "\App\Models\Customer" ${{ secrets.CIPHERSWEET_KEY }}

      - uses: actions/setup-node@v1
        name: Use Node.js 20
        with:
          node-version: 20
      - name: Install, build, test
        working-directory: ./core
        run: |
          npm install
          npm run build

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        working-directory: ./core
        env:
          DB_CONNECTION: pgsql
          DB_DATABASE: db_test_laravel
          DB_PORT: 55432
          DB_USERNAME: ${{ secrets.TEST_DB_USER }}
          DB_PASSWORD: ${{ secrets.TEST_DB_PWD }}
          CIPHERSWEET_KEY: ${{ secrets.CIPHERSWEET_KEY }}
        run: vendor/bin/phpunit --testdox
